export const APP_CONSTANTS = {
    PASSWORD_REGEX_DIGIT: /[0-9]/,
    PASSWORD_REGEX_UPPERCASE: /[A-Z]/,
    PASSWORD_REGEX_LOWERCASE: /[a-z]/,
    PASSWORD_REGEX_SPECIAL_CHAR: /[^A-Za-z0-9]/,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
  };
  