import { QuotableDesignEnum } from '@assets';
import { DesignFontEnum, IQuotableTemplate, QuotableTypeEnum } from '@interfaces';

export const quotableTemplateList: IQuotableTemplate[] = [
  //    QUOTABLE
  {
    name: 'Til Farmor/Farfar',
    type: QuotableTypeEnum.quotable,
    designProps: {
      showText: true,
      showTitle: false,
      title: '',
      text: 'Det eneste bedre \nend at have dig som \nMOR/FAR\n\nEr at mine børn har dig\nsom FARMOR/FARFAR',
      fontSize: 40,
      verticalPlacement: 35,
      designSrc: QuotableDesignEnum.frame11,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Til Mor/Far',
    type: QuotableTypeEnum.quotable,
    designProps: {
      showText: true,
      showTitle: false,
      title: '',
      text: 'Jeg elsker dig MOR/FAR,\nsom træer elsker vand og solskin.\nDu hjælper mig med at vokse,\ntrives og nå nye højder.\n\nDin SØN/DATTER\nNAVN',
      fontSize: 40,
      verticalPlacement: 50,
      designSrc: QuotableDesignEnum.frame2,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Til Mor/Far 2',
    type: QuotableTypeEnum.quotable,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Mor / Far',
      text: 'Jeg vil gerne takke dig\nfor at have spillet en så utrolig\nrolle i mit liv.\n\nJeg elsker dig nu og for evigt.\nNAVN',
      fontSize: 40,
      verticalPlacement: 50,
      designSrc: QuotableDesignEnum.frame1,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Kærligheds citat',
    type: QuotableTypeEnum.quotable,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Kærlighed',
      text: '\nVær ikke bange for,\ndu aldrig vil finde kærligheden.\n\nKærligheden vil finde dig,\nnår tiden er inde.',
      fontSize: 45,
      verticalPlacement: 50,
      designSrc: QuotableDesignEnum.noFrame,
      font: DesignFontEnum.argestadisplay,
    },
  },
  //   LOVE LETTER
  {
    name: 'Dit navn i skyrne',
    type: QuotableTypeEnum.loveLetter,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'Jeg skrev dit navn i skyerne,\nmen vinden blæste det væk.\n\nJeg skrev dit navn i sandet,\nmen bølgerne skyllede det væk.\n\nJeg skrev dit navn i mit hjerte,\nog for evigt vil det blive der.\n\n- Dit navn',
      fontSize: 26,
      verticalPlacement: 50,
      designSrc: QuotableDesignEnum.frame13,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Min elskede',
    type: QuotableTypeEnum.loveLetter,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'Jeg skrev dit navn i skyerne,\nmen vinden blæste det væk.\n\nJeg skrev dit navn i mit hjerte,\nog for evigt vil det blive der.\n\n- Dit navn',
      fontSize: 26,
      verticalPlacement: 30,
      designSrc: QuotableDesignEnum.frame14,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Blomsterkransen',
    type: QuotableTypeEnum.loveLetter,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'Jeg skrev dit navn i skyerne,\nmen vinden blæste det væk.\n\nJeg skrev dit navn i mit hjerte,\nog for evigt vil det blive der.\n\n- Dit navn',
      fontSize: 26,
      verticalPlacement: 50,
      designSrc: QuotableDesignEnum.frame16,
      font: DesignFontEnum.argestadisplay,
    },
  },
  //   BABY SIGN
  {
    name: 'Kærnefamilien',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: '01.01.2022\n\nMors navn & Fars navn.\n01.01.1990   01.01.1990',
      fontSize: 30,
      verticalPlacement: 81,
      designSrc: QuotableDesignEnum.frame20,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Børne tavle',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'With every newborn baby, a little sun rises.\n01.01.2022',
      fontSize: 30,
      verticalPlacement: 35,
      designSrc: QuotableDesignEnum.frame19,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Mor og barn',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: '\n01.01.21 - kl.00.00\n4000g - 50cm',
      fontSize: 30,
      verticalPlacement: 80,
      designSrc: QuotableDesignEnum.frame18,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Forældrene',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'Fødsel: 01.01.21\nVægt: 4000g\nHøjde: 50cm\nKlokken: 00.00\nDåb: 01.01.21',
      fontSize: 30,
      verticalPlacement: 83,
      designSrc: QuotableDesignEnum.frame20,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Den nyfødte',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'With every newborn baby, a little sun rises.\n01.01.2022',
      fontSize: 30,
      verticalPlacement: 78,
      designSrc: QuotableDesignEnum.frame21,
      font: DesignFontEnum.argestadisplay,
    },
  },
  {
    name: 'Barnets forældre',
    type: QuotableTypeEnum.babySign,
    designProps: {
      showText: true,
      showTitle: true,
      title: 'Fulde navn',
      text: 'Mors navn & Fars navn.\n01.01.2022',
      fontSize: 30,
      verticalPlacement: 78,
      designSrc: QuotableDesignEnum.frame20,
      font: DesignFontEnum.argestadisplay,
    },
  },
];
