import { TreeDesignEnum, BoxDesignEnum } from '@assets';
import { FamilyTreeFontEnum, Template } from '@interfaces';

const fourGenerationFamilyV1: Template = {
  name: 'fourGenerationFamilyV1',
  title: '4 Generationer',
  designProperties: {
    font: FamilyTreeFontEnum.argestadisplay,
    backgroundTreeDesign: TreeDesignEnum.tree2,
    boxSize: 17,
    banner: {
      text: 'Min Familie',
      style: 'first',
    },
    boxes: [
      {
        x: 1123,
        y: 882,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Mormor - ',
      },
      {
        x: 1023,
        y: 1179,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Mor - ',
      },
      {
        x: 583,
        y: 901,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Farfar - ',
      },
      {
        x: 208,
        y: 648,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box7,
        text: 'Oldefar - ',
      },
      {
        x: 745,
        y: 1188,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Far -',
      },
      {
        x: 1297,
        y: 430,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldemor -',
      },
      {
        x: 1519,
        y: 630,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Oldefar - ',
      },
      {
        x: 1269,
        y: 1416,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 873,
        y: 1447,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 392,
        y: 982,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Farmor - ',
      },
      {
        x: 508,
        y: 1429,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Barn -',
      },
      {
        x: 1619,
        y: 733,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldemor -',
      },
      {
        x: 1144,
        y: 333,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldefar - ',
      },
      {
        x: 648,
        y: 346,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box4,
        text: 'Oldefar - ',
      },
      {
        x: 1322,
        y: 970,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Morfar -',
      },
      {
        x: 505,
        y: 442,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Oldemor -',
      },
      {
        x: 58,
        y: 754,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Oldemor -',
      },
    ],
  },
};

const fourGenerationFamilyV2: Template = {
  name: 'fourGenerationFamilyV2',
  title: '4 Generationer',
  designProperties: {
    font: FamilyTreeFontEnum.argestadisplay,
    backgroundTreeDesign: TreeDesignEnum.tree1,
    boxSize: 17,
    banner: {
      text: 'Min Familie',
      style: 'first',
    },
    boxes: [
      {
        x: 1123,
        y: 882,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Mormor - ',
      },
      {
        x: 1023,
        y: 1179,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Mor - ',
      },
      {
        x: 583,
        y: 901,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Farfar - ',
      },
      {
        x: 208,
        y: 648,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box7,
        text: 'Oldefar - ',
      },
      {
        x: 745,
        y: 1188,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Far -',
      },
      {
        x: 1297,
        y: 430,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldemor -',
      },
      {
        x: 1519,
        y: 630,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Oldefar - ',
      },
      {
        x: 1269,
        y: 1416,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 873,
        y: 1447,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 392,
        y: 982,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Farmor - ',
      },
      {
        x: 508,
        y: 1429,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Barn -',
      },
      {
        x: 1619,
        y: 733,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldemor -',
      },
      {
        x: 1144,
        y: 333,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Oldefar - ',
      },
      {
        x: 648,
        y: 346,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box4,
        text: 'Oldefar - ',
      },
      {
        x: 1322,
        y: 970,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Morfar -',
      },
      {
        x: 505,
        y: 442,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Oldemor -',
      },
      {
        x: 58,
        y: 754,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Oldemor -',
      },
    ],
  },
};

const threeGenerationFamilyV1: Template = {
  name: 'threeGenerationFamilyV1',
  title: '3 Generationer',
  designProperties: {
    font: FamilyTreeFontEnum.calendas,
    backgroundTreeDesign: TreeDesignEnum.tree1,
    boxSize: 23,
    banner: {
      text: 'Min Familie',
      style: 'first',
    },
    boxes: [
      {
        x: 96.25100582770449,
        y: 598.8436029357979,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Farmor - ',
      },
      {
        x: 389.6357074931118,
        y: 470.8779351881201,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Farfar - ',
      },
      {
        x: 233.5800151178952,
        y: 1182.4918924191072,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Barn -',
      },
      {
        x: 1450.8144156445833,
        y: 586.3591475457804,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Morfar -',
      },
      {
        x: 773.5327107361438,
        y: 1341.668698641828,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 998.2529077564559,
        y: 879.7438492111874,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Mor - ',
      },
      {
        x: 1176.1563970642023,
        y: 452.1512521030943,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Mormor - ',
      },
      {
        x: 595.629221428397,
        y: 882.8649630586918,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Far -',
      },
      {
        x: 1325.9698617444103,
        y: 1170.00743702909,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
    ],
  },
};

const threeGenerationFamilyV2: Template = {
  name: 'threeGenerationFamilyV2',
  title: '3 Generationer',
  designProperties: {
    font: FamilyTreeFontEnum.calendas,
    backgroundTreeDesign: TreeDesignEnum.tree2,
    boxSize: 23,
    banner: {
      text: 'Min Familie',
      style: 'first',
    },
    boxes: [
      {
        x: 96.25100582770449,
        y: 598.8436029357979,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Farmor - ',
      },
      {
        x: 389.6357074931118,
        y: 470.8779351881201,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Farfar - ',
      },
      {
        x: 233.5800151178952,
        y: 1182.4918924191072,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Barn -',
      },
      {
        x: 1450.8144156445833,
        y: 586.3591475457804,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box3,
        text: 'Morfar -',
      },
      {
        x: 773.5327107361438,
        y: 1341.668698641828,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 998.2529077564559,
        y: 879.7438492111874,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Mor - ',
      },
      {
        x: 1176.1563970642023,
        y: 452.1512521030943,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Mormor - ',
      },
      {
        x: 595.629221428397,
        y: 882.8649630586918,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Far -',
      },
      {
        x: 1325.9698617444103,
        y: 1170.00743702909,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
    ],
  },
};

const twoGenerationFamily: Template = {
  name: 'twoGenerationFamily',
  title: 'Kernefamilien',
  designProperties: {
    font: FamilyTreeFontEnum.calendas,
    backgroundTreeDesign: TreeDesignEnum.tree2,
    boxSize: 31,
    banner: {
      text: 'Min Familie',
      style: 'first',
    },
    boxes: [
      {
        x: 751.6849138036134,
        y: 417.81899978054696,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Barn -',
      },
      {
        x: 86.8876642851917,
        y: 623.8125137158324,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Barn -',
      },
      {
        x: 442.69464290068515,
        y: 1129.4329570115337,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Far -',
      },
      {
        x: 967.0417692814124,
        y: 1129.4329570115337,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box6,
        text: 'Mor - ',
      },
      {
        x: 1369.6654556094707,
        y: 636.2969691058499,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box4,
        text: 'Barn -',
      },
    ],
  },
};

const friendTreeV1: Template = {
  name: 'friendTreeV1',
  title: 'Vennetræet',
  designProperties: {
    font: FamilyTreeFontEnum.calendas,
    backgroundTreeDesign: TreeDesignEnum.tree1,
    boxSize: 31,
    banner: {
      text: 'Vennetræet',
      style: 'first',
    },
    boxes: [
      {
        x: 1101.2496647240985,
        y: 1113.827387774012,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Ven',
      },
      {
        x: 86.8876642851917,
        y: 639.4180829533541,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box8,
        text: 'Veninde',
      },
      {
        x: 283.5178366779643,
        y: 1113.827387774012,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box1,
        text: 'Ven ',
      },
      {
        x: 736.0793445660918,
        y: 321.0644705079128,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Veninde',
      },
      {
        x: 1369.6654556094707,
        y: 636.2969691058499,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box5,
        text: 'Ven',
      },
    ],
  },
};

const partnerTreeV1: Template = {
  name: 'partnerTreeV1',
  title: 'Til hende',
  designProperties: {
    font: FamilyTreeFontEnum.calendas,
    backgroundTreeDesign: TreeDesignEnum.tree1,
    boxSize: 40,
    banner: {
      text: 'Kærligheds træet',
      style: 'first',
    },
    boxes: [
      {
        x: 285.7142857142857,
        y: 800,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box4,
        text: 'Dig',
      },
      {
        x: 1000,
        y: 800,
        previousX: 0,
        previousY: 0,
        dragging: false,
        boxDesign: BoxDesignEnum.box2,
        text: 'Partner',
      },
    ],
  },
};

export const templateList = {
  fourGenerations: fourGenerationFamilyV1,
  threeGenerations: threeGenerationFamilyV1,
  twoGenerations: twoGenerationFamily,
  friendTree: friendTreeV1,
  partnerTree: partnerTreeV1,
};

enum TemplateListEnum {
  fourGenerations = 'fourGenerationFamilyV1',
  threeGenerations = 'threeGenerationFamilyV1',
  twoGenerations = 'twoGenerationFamily',
  friendTree = 'friendTreeV1',
  partnerTree = 'partnerTreeV1',
}
