export enum QuotableDesignEnum {
  noFrame = 'assets/quotable/frame-design/frame0-no-design.svg',
  frame1 = 'assets/quotable/frame-design/frame1.svg',
  frame2 = 'assets/quotable/frame-design/frame2.svg',
  frame3 = 'assets/quotable/frame-design/frame3.svg',
  frame4 = 'assets/quotable/frame-design/frame4.svg',
  frame5 = 'assets/quotable/frame-design/frame5.svg',
  frame6 = 'assets/quotable/frame-design/frame6.svg',
  frame7 = 'assets/quotable/frame-design/frame7.svg',
  frame8 = 'assets/quotable/frame-design/frame8.svg',
  frame9 = 'assets/quotable/frame-design/frame9.svg',
  frame10 = 'assets/quotable/frame-design/frame10.svg',
  frame11 = 'assets/quotable/frame-design/frame11.svg',
  frame12 = 'assets/quotable/frame-design/frame12.svg',
}

export enum QuotableDesignNameDanishEnum {
  noFrame = 'Ingen Ramme',
  frame1 = 'Simpel Stil',
  frame2 = 'Frugt Ramme',
  frame3 = 'Simpel Klassisk',
  frame4 = 'Klassisk U',
  frame5 = 'Klassisk OU',
  frame6 = 'Klassisk XL',
  frame7 = 'Simpel Rose',
  frame8 = 'Guldfisk',
  frame9 = 'Antik Ramme',
  frame10 = 'Blomster Buket',
  frame11 = 'Simpel Blomst U',
  frame12 = 'Blomsterkrans',
}

export enum QuotableDesignNameEnglishEnum {
  noFrame = 'No Frame',
  frame1 = 'Simple Style',
  frame2 = 'Fruit Frame',
  frame3 = 'Simple Classic',
  frame4 = 'Classic U',
  frame5 = 'Classic UO',
  frame6 = 'Classic XL',
  frame7 = 'Simple Rose',
  frame8 = 'Goldfish',
  frame9 = 'Antique Frame',
  frame10 = 'Flower Bouquet',
  frame11 = 'Simple Flower U',
  frame12 = 'Flower Wreath',
}
