server.port=5000
# Database connection
spring.datasource.url=${TREECREATE_JDBC_URL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
# Email sending
# note: usernames aka specific domains are hardcoded in config/MailConfig and mail/MailService
spring.mail.host=send.one.com
spring.mail.password=${TREECREATE_MAIL_PASS}
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Okta authentication
okta.oauth2.client-id=0oamnkb1cuWpU2TTh5d6
okta.oauth2.issuer=https://dev-81944821.okta.com/oauth2/default
