export enum LocalStorageVars {
  locale = 'locale',
  cookiesAccepted = 'cookiesAccepted',
  authUser = 'authUser',
  eventLogUserId = 'eventLogUserId',
  designFamilyTree = 'designFamilyTree',
  designQuotable = 'designQuotable',
  designLoveLetter = 'designLoveLetter',
  designBabySign = 'designBabySign',
  discount = 'discount',
  plantedTrees = 'plantedTrees',
  transactionItems = 'transactionItems',
  hasSeenNewsletterModal = 'hasSeenNewsletterModal',
  firstVisit = 'firstVisit',
}
