# This file has to be executed with docker-compose push

version: '3.8'

services:
  #### DEV START ####

  api-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/api/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:api-dev

  webstore-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/webstore/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:webstore-dev

  admin-page-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/admin-page/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:admin-page-dev
  #### DEV END ####

  #### PROD START ####

  api-prod:
    profiles: [prod]
    build:
      dockerfile: .deploy/api/Dockerfile
      context: ../.
      args:
        ENV: 'prod'
    image: kwandes/treecreate-v2:api-prod

  webstore-prod:
    profiles: [prod]
    build:
      dockerfile: .deploy/webstore/Dockerfile
      context: ../.
      args:
        ENV: 'prod'
    image: kwandes/treecreate-v2:webstore-prod

  admin-page-prod:
    profiles: [prod]
    build:
      dockerfile: .deploy/admin-page/Dockerfile
      context: ../.
      args:
        ENV: 'prod'
    image: kwandes/treecreate-v2:admin-page-prod

  #### PROD END ####
