# ENV syntax explanation:
# :? means that the ENV has to be set & not be blank
# ?  means that the ENV must be set but may be blank
# In both cases, due to the '?' it will give an error if the ENV is not set

# env_file tag is currently not working. Its in the file anyhow in hopes that
#  in the future it will work.
# Currently you need to call the docker-compose with '--env-file' and point it
#  to the correct file.

# This file has to be executed with docker-compose push

version: '3.8'

services:
  #### DEV START ####

  api-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/api/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:api-dev

  webstore-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/webstore/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:webstore-dev

  admin-page-dev:
    profiles: [dev]
    build:
      dockerfile: .deploy/admin-page/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:admin-page-dev
  #### DEV END ####

  #### PROD START ####

  api-prod:
    profiles: [prod]
    environment:
      - ENV=prod
    build:
      dockerfile: .deploy/api/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:api-prod

  webstore-prod:
    profiles: [prod]
    environment:
      - ENV=prod
    build:
      dockerfile: .deploy/webstore/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:webstore-prod

  admin-page-prod:
    profiles: [prod]
    environment:
      - ENV=prod
    build:
      dockerfile: .deploy/admin-page/Dockerfile
      context: ../.
    image: kwandes/treecreate-v2:admin-page-prod

  #### PROD END ####
