# Workflow name
name: Deploy application

# Triggers
on:
  workflow_dispatch:
  push:
    branches:
      - admin-page
      - development
      - production


# Actions
jobs:
  deploy:
 
    runs-on: ubuntu-latest  
    steps:
      - name: Set build profile

        # Set default state of PROFILE to dev
        run: echo "PROFILE=dev" >> $GITHUB_ENV
        # If branch is production sed PROFILE to prod
      - if: github.ref == 'refs/heads/production'
        run: echo "PROFILE=prod" >> $GITHUB_ENV

      - name: Print PROFILE env
        shell: bash
        run: echo profile is :${PROFILE}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker-compose build
        shell: bash
        run: docker-compose -f .deploy/docker-compose-build.yml --profile ${PROFILE} build

      - name: Docker-compose push
        shell: bash 
        run: docker-compose -f .deploy/docker-compose-build.yml --profile ${PROFILE} push 

      - name: SSH into AWS EC2 instance
        shell: bash
        run: echo "Connecting to EC2 instance"

      - name: Run docker-compose up in EC2 instance
        shell: bash
        # SSH to AWS instance
        # run docker-compose -f .deploy/docker-compose-run.yml --profile ${PROFILE} up
        run: echo "Running docker-compose up"
