# Workflow name
name: Deploy application

# Triggers
on:
  workflow_dispatch:
  push:
    branches:
      - admin-page
      - development
      - production

# Actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set build profile

        # Set default state of PROFILE to dev
        run: echo "PROFILE=dev" >> $GITHUB_ENV
        # If branch is production sed PROFILE to prod
      - if: github.ref == 'refs/heads/production'
        run: echo "PROFILE=prod" >> $GITHUB_ENV

      - name: Print PROFILE env
        shell: bash
        run: echo profile is :${PROFILE}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker-compose build
        shell: bash
        run: docker-compose -f .deploy/docker-compose.build.yml --profile ${PROFILE} build

      - name: Docker-compose push
        shell: bash
        run: docker-compose -f .deploy/docker-compose.build.yml --profile ${PROFILE} push

      - name: Execute docker-compose up through SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: PROFILE
          script: |
            echo $PROFILE
            ~/scripts/login-and-update.sh $PROFILE up -d
