# Validate code for potential errors
# Triggered on pull requests
name: Lint CI
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install and Lint
        run: |
          npm ci
          npm run lint
